[package]
name = "socket_phone"
# copy of main project version
version = "0.1.6"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "~0.21"
tokio = { version = "~1", features = ["full"] }
log = "~0.4"
android_logger = "~0.15"
bytes = { version = "~1.12"}
uuid = { version = "~1.26", features = ["v4", "serde"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures-util = { version = "0.3", features = ["sink"] }
once_cell = { version = "~1.21.4" }
chrono = { version = "~0.4" }
aes-gcm = { version = "~0.11" }
hex = "*"
rand = { version = "~0.10" }
sha1 = "~0.11"
